"""Painel HTML local de revisão: filtros, notas e exportação, sem serviços externos."""
import json
from pathlib import Path

def gerar_painel(frame,destino):
    payload=json.dumps(frame.fillna('').to_dict('records'),ensure_ascii=False).replace('<','\\u003c').replace('>','\\u003e').replace('&','\\u0026')
    html=MODELO.replace('__DADOS_JSON__',payload)
    Path(destino).write_text(html)

MODELO='''<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Revisão das divergências — SMS</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f4f6f8;color:#172937;font:16px/1.55 system-ui,sans-serif}main{max-width:1120px;margin:auto;padding:30px 22px}h1{font-size:30px;margin:0 0 8px}h2{font-size:19px}p{margin:8px 0 16px}.muted{color:#506372}.toolbar{display:flex;gap:12px;flex-wrap:wrap;padding:18px;background:white;border-radius:12px;margin:22px 0}label{display:flex;flex-direction:column;gap:5px;font-size:14px;font-weight:600}input,select,textarea,button{font:inherit;padding:10px;border:1px solid #bbc7cf;border-radius:6px;background:white;color:#172937}input[type=search]{min-width:260px}button{cursor:pointer;background:#176b87;color:white;border:0}button:disabled{opacity:.4;cursor:default}.secondary{background:#e6edf1;color:#172937}article{background:white;padding:22px;border-radius:12px;margin:18px 0;border:1px solid #d7e0e6}article h2{margin:0 0 10px;overflow-wrap:anywhere}.message{white-space:pre-wrap;border-left:4px solid #176b87;background:#f2f7f9;padding:14px;overflow-wrap:anywhere}.values{display:flex;gap:30px;margin:16px 0}.values strong{font-size:23px;display:block}.evidence{white-space:pre-wrap;overflow-wrap:anywhere;font-family:ui-monospace,monospace;font-size:13px;background:#f4f6f8;padding:12px}.review{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:16px}.review label:last-child{grid-column:1/-1}textarea{min-height:65px;resize:vertical}nav{display:flex;gap:14px;align-items:center}.status{font-weight:600}small{color:#506372}summary{cursor:pointer;font-weight:600}#notice{color:#176b87;font-weight:600}.filelabel{font-weight:normal}input[type=file]{max-width:240px}@media(max-width:650px){.review{grid-template-columns:1fr}.values{gap:15px}h1{font-size:24px}input[type=search]{min-width:100%}}
</style><main>
<h1>Revisão das divergências de SMS</h1>
<p>Compare o rótulo original com a saída do script e registre sua decisão. Uma divergência não prova que o original está errado. A definição e a evidência ajudam na revisão.</p>
<p class="muted">As decisões ficam nesta página enquanto ela estiver aberta. Use <b>Baixar revisão CSV</b> para salvar. Na próxima abertura, importe esse CSV para continuar. Nada altera o dataset original automaticamente.</p>
<div class="toolbar">
<label>Feature<select id="feature"><option value="">Todas as features</option></select></label>
<label>Situação<select id="state"><option value="">Todas</option><option value="pendente">Pendentes</option><option value="revisado">Com decisão</option></select></label>
<label>Buscar mensagem<input type="search" id="search" placeholder="Palavra ou trecho do SMS"></label>
<button id="download">Baixar revisão CSV</button><label class="filelabel">Continuar uma revisão<input id="import" type="file" accept=".csv,text/csv"></label>
</div><p id="notice" aria-live="polite"></p><p id="counts" class="status"></p><nav><button id="prev" class="secondary">Anterior</button><span id="page"></span><button id="next" class="secondary">Próxima</button></nav><section id="records"></section>
<script type="application/json" id="data">__DADOS_JSON__</script>
<script>
'use strict';
const rows=JSON.parse(document.getElementById('data').textContent);const $=id=>document.getElementById(id);let page=0;const size=15;
const fields=rows.length?Object.keys(rows[0]):['id_divergencia','decisao_humana','valor_decidido','comentario_revisor'];
const decisions=[['','Pendente'],['original','Original está correto'],['gerado','Gerado está correto'],['outro','Outro valor'],['inconclusivo','Inconclusivo']];
for(const f of [...new Set(rows.map(r=>r.feature))].sort()){const o=document.createElement('option');o.value=f;o.textContent=f;$('feature').append(o);}
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function filtered(){const q=$('search').value.toLocaleLowerCase();return rows.filter(r=>(!$('feature').value||r.feature===$('feature').value)&&(!$('state').value||($('state').value==='pendente'?!r.decisao_humana:!!r.decisao_humana))&&(!q||r.Mensagem.toLocaleLowerCase().includes(q)));}
function render(){const found=filtered(),pages=Math.max(1,Math.ceil(found.length/size));page=Math.min(page,pages-1);$('records').replaceChildren();$('counts').textContent=found.length+' divergências no filtro · '+rows.filter(r=>r.decisao_humana).length+' com decisão / '+rows.length+' no total';$('page').textContent='Página '+(page+1)+' de '+pages;$('prev').disabled=page===0;$('next').disabled=page>=pages-1;
for(const r of found.slice(page*size,(page+1)*size)){const card=el('article');card.append(el('h2',r.feature),el('small','Registro original '+r.registro_original+' · PDF, página '+r.pagina_pdf),el('p',r.Mensagem,'message'));const vals=el('div',undefined,'values');for(const [label,value]of [['Original',r.valor_original],['Gerado',r.valor_gerado]]){const v=el('div',label);v.append(el('strong',value));vals.append(v);}card.append(vals);const det=el('details');det.append(el('summary','Ver definição, método e evidência'),el('p',r.definicao),el('p',r.criterio_e_limite),el('p','Método: '+r.metodo),el('div',r.evidencia_script,'evidence'));card.append(det);const rev=el('div',undefined,'review');const l=el('label','Sua decisão');const sel=el('select');sel.setAttribute('aria-label','Decisão '+r.id_divergencia);for(const [v,t]of decisions){const o=el('option',t);o.value=v;sel.append(o);}sel.value=r.decisao_humana||'';l.append(sel);const lv=el('label','Valor decidido (obrigatório se escolher Outro)');const value=el('input');value.value=r.valor_decidido||'';lv.append(value);sel.onchange=()=>{r.decisao_humana=sel.value;r.valor_decidido=sel.value==='original'?r.valor_original:sel.value==='gerado'?r.valor_gerado:'';value.value=r.valor_decidido;render();$('notice').textContent='Decisão registrada nesta página. Baixe o CSV para salvar.';};value.oninput=()=>r.valor_decidido=value.value;const ln=el('label','Comentário');const note=el('textarea');note.value=r.comentario_revisor||'';note.oninput=()=>r.comentario_revisor=note.value;ln.append(note);rev.append(l,lv,ln);card.append(rev);$('records').append(card);}}
for(const id of ['feature','state','search'])$(id).oninput=()=>{page=0;render();};$('prev').onclick=()=>{page--;render();};$('next').onclick=()=>{page++;render();};
function parseCSV(s){s=s.replace(/^\\uFEFF/,'');let out=[],row=[],cell='',quote=false;for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'){if(quote&&s[i+1]==='"'){cell+='"';i++;}else quote=!quote;}else if(c===','&&!quote){row.push(cell);cell='';}else if((c==='\\n'||c==='\\r')&&!quote){if(c==='\\r'&&s[i+1]==='\\n')i++;row.push(cell);if(row.some(x=>x!==''))out.push(row);row=[];cell='';}else cell+=c;}if(quote)throw Error('Aspas não fechadas no CSV.');if(cell||row.length){row.push(cell);out.push(row);}return out;}
$('import').onchange=async()=>{try{const file=$('import').files[0];if(!file)return;const data=parseCSV(await file.text());const header=data.shift();const required=['id_divergencia','decisao_humana','valor_decidido','comentario_revisor'];if(!required.every(x=>header.includes(x)))throw Error('Use o CSV exportado por esta revisão.');const map=new Map(rows.map(r=>[r.id_divergencia,r]));let count=0;const pending=[],seen=new Set();for(const vals of data){if(vals.length!==header.length)throw Error('Linha com número de campos inválido.');const a=Object.fromEntries(header.map((h,i)=>[h,vals[i]]));if(seen.has(a.id_divergencia))throw Error('ID de revisão repetido.');seen.add(a.id_divergencia);if(!decisions.some(d=>d[0]===a.decisao_humana))throw Error('Decisão desconhecida.');const r=map.get(a.id_divergencia);if(!r)continue;pending.push([r,a]);}for(const [r,a]of pending){for(const f of required.slice(1))r[f]=a[f];count++;}render();$('notice').textContent=count+' registros importados. IDs ausentes nesta versão foram ignorados.';}catch(e){$('notice').textContent='Importação não concluída: '+e.message;}};
$('download').onclick=()=>{const quote=v=>'"'+String(v??'').replaceAll('"','""')+'"';const text='\\uFEFF'+[fields,...rows.map(r=>fields.map(f=>r[f]))].map(a=>a.map(quote).join(',')).join('\\r\\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8;'}));const a=el('a');a.href=url;a.download='revisao_humana.csv';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('notice').textContent='CSV exportado. Guarde-o para continuar sua revisão.';};render();
</script></main></html>'''
